; Project-owned Chinese translations for the installer pages in use.
; Unspecified diagnostic messages fall back to Inno Setup's Default.isl.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
DialogFontName=Microsoft YaHei UI

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
InformationTitle=提示
ConfirmTitle=确认
ErrorTitle=错误
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)…
ButtonWizardBrowse=浏览(&R)…
ButtonNewFolder=新建文件夹(&M)
ClickNext=点击“下一步”继续，或点击“取消”退出安装。
BrowseDialogTitle=选择文件夹
BrowseDialogLabel=选择安装位置，然后点击“确定”。
NewFolderName=新建文件夹
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。确定退出吗？%n%n可以稍后重新运行安装程序。
WelcomeLabel1=欢迎安装 [name]
WelcomeLabel2=即将在本机安装 [name/ver]。%n%n点击“下一步”继续。程序安装到当前用户目录，无需管理员权限。若缺少 Microsoft WebView2 运行库，安装程序会联网补齐。
WizardSelectDir=选择安装位置
SelectDirDesc=选择安装位置
SelectDirLabel3=安装程序将把 [name] 安装到以下文件夹。
SelectDirBrowseLabel=点击“下一步”继续，或点击“浏览”选择其他文件夹。
DiskSpaceGBLabel=至少需要 [gb] GB 可用磁盘空间。
DiskSpaceMBLabel=至少需要 [mb] MB 可用磁盘空间。
DirExistsTitle=文件夹已存在
DirExists=文件夹：%n%n%1%n%n已存在。继续安装到此文件夹吗？
DirDoesntExistTitle=创建文件夹
DirDoesntExist=文件夹：%n%n%1%n%n不存在。现在创建吗？
WizardSelectTasks=选择附加任务
SelectTasksDesc=选择附加任务
SelectTasksLabel2=选择安装时需要执行的附加任务，然后点击“下一步”。
WizardReady=准备安装
ReadyLabel1=准备安装
ReadyLabel2a=点击“安装”开始。若要修改设置，请点击“上一步”。
ReadyLabel2b=点击“安装”开始。
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单：
ReadyMemoTasks=附加任务：
WizardPreparing=正在准备安装
PreparingDesc=正在准备安装
CannotContinue=当前无法继续安装。请点击“取消”退出后重试。
ApplicationsFound=以下程序正在使用需要更新的文件。请先退出这些程序，或允许安装程序关闭它们。
CloseApplications=自动关闭这些程序(&A)
DontCloseApplications=暂不关闭这些程序(&D)
ErrorCloseApplications=部分程序未能自动关闭。请手动退出正在使用浮词程序文件的应用后重试。
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候…
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已安装到本机。
FinishedLabel=[name] 已安装到本机。可以通过桌面或开始菜单快捷方式启动。
ClickFinish=点击“完成”退出安装程序。
StatusExtractFiles=正在复制程序文件…
StatusCreateIcons=正在创建快捷方式…
StatusCreateIniEntries=正在保存设置…
StatusCreateRegistryEntries=正在登记应用…
StatusSavingUninstall=正在保存卸载信息…
StatusRunProgram=正在完成安装…
ConfirmUninstall=确定卸载 %1 吗？%n%n登录会话和个人设置将保留。
WizardUninstalling=正在卸载
UninstallStatusLabel=正在卸载 %1，请稍候…
UninstalledAll=%1 已卸载。个人数据已保留，重新安装后可继续使用。
UninstallDisplayNameMarkCurrentUser=当前用户
UninstallDisplayNameMark64Bit=64 位
